import Head from 'next/head'

export default function Conversation() {
  return (
    <div>
      <Head>
        <title>Conversational ninja</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Talking magically</h1>
    <p>I could have named this article - the art of conversation, but i would like to keep it basic and not get too flowery. Point is to not get stuck in the words too much and talk about principles and action. Now you are well versed with the concepts of body language. Now next step is to understand that when you approach someone what and how would you talk.</p>
    <p>Remeber the most basic underlying principle of this system is demonstrating high value. Before you approach someone, you have no value. Once you make the approach, you have to immeidately convert that value to a high value rather than a low value. You have learnt the body language principles and body languageis used to demontrate high value. But most human interation would be incomplete without a conversation.</p>
    <h2>What to talk?</h2>
    <p>When you enter teh room, you have to read it. Is it a formal or informal ocassion. What are the profession and interests of the people in that room. Are the gentry liberal or conservative. What can be their interests. Then you have to talk in accordance with that. However, most of the people, especially the intorverted ones will still have trouble talking to the people, because of a classic issue - "I don't know what to talk?". Don't worry if you do the next exercise properly, within a couple of weeks you'll be a conversational ninja.</p>
    <h2>Exercise: Conversational ninja</h2>
    <p>This one exercise has changed life of many of my students, especially the introverted ones.</p>
    <ol>
        <li>Switch on the selfie camera of your smartphone in the video mode or just satnd in front of a mirror.</li>
        <li>You have to do it for 10 minutes daily</li>
        <li>Pick one word(noun), which can be anything like - car, tree, umbrella, or any random thing</li>
        <li>Speak on it for 20 seconds</li>
        <li>You can speak anything about it. For example, if the word is car - you can say that i like red cars, and i like to take them on the long drives, my favourite brand of car is Jaguar, but i hate SUVs. etc etc</li>
        <li>After 20-30 seconds change the topic</li>
        <li>Next topic should be the a word from the last sentence of the previous topic. For example, it can be Jagur. You can say - jaguars are founds in the rainsforests of amazon, they're from the cat family but are very ferocious. I would like to see them in the Amazon jungles.</li>
        <li>Continue this for 10 minutes. Do this daily and in a couple of weeks you'll find that you'll be able to speak on any topic for long.</li>
    </ol>
    <h2>Demonstrating high value through words</h2>
    <p>Now you know how to read the room and how to talk. So when you enter a romm and read it you have to approach anyone you like, they maybe the waiter there or the most important person there. It doesn't matter. The point is, as soon as you enter the venue, your main focus sould be initiating a conversation with someone. Choose a person, make a genuine observation about them and with a genuine interest and friendliness make the approach.</p>
    <p>Since, your intention is to grow your professional network, it's better to make an observation related to their professional (and not personal) behaviour or achievement, and then begin the conversation with that. For example, you see the CEO of a company standing across the room, you have an idea, if possible take out your phone go to the breakout and have a quick glance at them and their company's profile. Then when you're back just approach them with great enthusiasm and body language. When you start talking, don't stop it for 10-15 seconds. Be very expressive in your speech. In 15 seconds the person will realise that you're also a person of high value. When they realise this, show your humility and eagerness to learn from them. Talk how you were impressed by their posrtfolo and ask them various questions. But, for the the first 15-30 seconds you have to demostrate the value yourself by speaking yourself out loudly and in an expressive manner with a laid back body language, smiling face, great eye contact. If you don't have prior information about the person, just start the conversation with what you feel like - eg just ask a question - are you a journalist? then without waiting for the reply or a yes/no reply, self express yourself for next 15-30 seconds, until they recognize your high value. Then you can resume the conversation in a normal to and fro manner. </p>
    <p>Also, note that as in the exercise you ahve to change the topic every 20 seconds, until you stumble upon a topic that is of interest for both you and the person you're talking to.</p>
    <p>Later parts of this process wil be expalined further in the system.</p>
    <h2>Fallback material</h2>
    <p>There would be times when irrespective of anything you do or observe, you will fall short of words. For that time you have to prepare a fallback material. For example, you should have a materail for introduction ready for different occassions. At certain times you may just get blank. Fallback material would come in handy at that time. It is good to have a set of fallback material for the following scenarios:</p>
    <ol>
        <li>Introduction (for formal and informal occassions)</li>
        <li>What do you do?</li>
        <li>What brought you here?</li>
        <li>What inspired you to adopt this profession?</li>
        <li>What were the challanges that you faced in your journey?</li>
    </ol>
    <p>You will realize that there is no end to the material that you can use as a fallback. Infact that is what everyone of us do. If someone asks us about our favourite movie we don't have to think deeply every time. We already know and rememeber it. But to accelerate this process you have to deliberate create some basic fallback material and then when you start to practice, you'll have to add more to it. You can add to apps like Anki, so that you can remember it better through active recall and spaced repetition. Also, make sure that you don't overexaggerate or write false things in your fallback material. Keep it genuine.</p>
    <h3>Exercise</h3>
    <p>Your next exercise is to imagine the events and venues you would visit for networking, like a conference, a professional meetup, a professional lunch or dinner, an amusement park, a wedding or a random place where you're a stranger. How would you answer each of the above questions there? Write them down. Next, imagine five more questions that you think can be asked to you in these situations and write answer to all of them. You have to activelly recall these answers along with spaced repetition. Rememeber to be genuine in your answers and never write false things about yourself.</p>

      
    </div>
  )
}