import Head from 'next/head'

export default function Exercising() {
  return (
    <div>
      <Head>
        <title>Exercising</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Exercise</h1>
    <p>The shape of your body should have absolutely no bearing on how you feel. If you've love handles or are even overweight, it should not have any impact on your confidence.</p>
    <p>However, physical exercise is very important for your mental and physical health, and hence it does have an influence on how you feel irrespective of you knowing it. I would recommend that you do a minimum of 60 minutes of physical activity per day. It can be anything, lifting weights, yoga, jogging, or walking. Not to mention that heavy cardio without lifting weights/muscle-building activities, may cause muscle loss and further problems, also if you're new to lifting weights you should learn so by doing it under a professional trainer for a couple of months. Diet is an important part of maintaining your body, and exercise without a proper scientific diet will be ineffective. However, for the sake of our system, if you're a beginner and don't exercise currently just do 60 min brisk walk daily, that should be sufficient. Also, take a light diet - fewer carbs, less sugar, more proteins, and you're golden.</p>
    <p>Whatever be the case, don't let your current body shape dictate your self-confidence. In any case, if you've low self-confidence, we're going to deal with it in the later steps.</p>
    <p>So beginning from today start doing a minimum of 60 mins of exercise or physical activity daily. </p>

    </div>
  )
}