import Head from 'next/head'

export default function Followingup() {
  return (
    <div>
      <Head>
        <title>Following up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Following up and making them part of your network</h1>
    <p>Until you follow up with people who you exchanged contact information with, they'll loose connnection with you really soon. They won't necessarily forget you, but that special connection will really fade away. So, you need to revive the connection ocassionally and make them remember you. How you do that? After the first meeting, you've to send them an email within three days. It can even be sent on the first day, but it should be less than three days. The email should contain three things:</p>
    <ol>
        <li>It should have the same connection factor that you had in the real event eg. hey, john it was really awesome meeting and discussing about traveling with you.</li>
        <li>Secondly, it should provide value about the same thing. For eg, i remember you mentioned your plan of travelling to portugal next month, i remember a an awesome bakery from my trip to lisbon the last year, it serves awesome lemon cakes, so do visit it if you happen to visit lisbon.</li>
        <li>Appreciation message - eg Anyways, it way really great meeting you, hope to see/connect with you soon again</li>
    </ol>
    <p>If you can find them on linkedin, you should add them to it on fifth or sixth day. Never send a connection request without a message </p>
    <p>Then you should should revive the connection again on 15th day by sending a an email or linkedin. After that do it every once in 30-45 days. Once you feel taht you have established enough connection with them, send them friend or follow requests on other social media platforms like facebook or instagram.</p>
    <p>thanks Leon Noel for his kind suggestion</p>
    <h2>Maintaining the sheet:</h2>
    <p>Once you start networking and meeting with people regularly, you'll start forgetting abot them frequently. You may forget their name, interests, the event, or the place you met at. TO avoid that, you should have a spreadsheet or an excel file, in which you have to write all the necessary information related to them - like their name, the place and event you met them at, what was the ocassion, what were their interests and special points in your conversation, anyother thing that you would like to add.</p>

    </div>
  )
}