import Head from 'next/head'

export default function Positivity() {
  return (
    <div>
      <Head>
        <title>Grooming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <h1>Grooming</h1>
        <p>There is a lot to grooming. It's a humongous field in itself. But dont worry, you don't need much of it. There are two parts to it.</p>
        <h2>If you're a man</h2>
        <p>Your inner confidence, body language, sub communication and communication skills are immensly more importamt and attractive features than just grooming. I would say that in whole of this dynamics, grooming just matters 1%. That's it. Period. Don't think about the grooming more than i tell you to. Now, why I am saying so? Just imagine a very dressed person physically fit, smelling great, having a ripped ripped body but still having a slouched posture, unconfident voice and having lack of self confidence, and a desperate vibe. Now, imagine another person, 5'6 in height, wearing normal trousers and shirt, wearing specs, having a laid back confident posture, a great warm smile and a loud and friendly and confident voice and vibe. Who do you think, you would give more value and respect?</p>
        <p>Now, why grooming is necessary, even though it's 1%. You would be tempted to think, that it will make you feel confident yourself. A classic mistake. Yes, proper grooming will indeed make you feel 'self confident' to some extent, but you've to realise that a self confidence that is  dependent in your grooming would be fargile and dependent on your clothes and brand of your perfume. I want you to be confident even when you've not bathed or brushed your teeth, for ten days! Yes, I want that your sense of self is impenetrable by your state of mind, body or external situation! So, the question still remains unanswered - why is grooming still important? The answer is, it's a tactic. As simple as that. When you approch someone who doesn't know you, it will take their mind a few seconds (~1 to 10sec) to register your presence make first impression of you. In a a few seconds, their mind will make an important decision about you. That decision would be - how important you are.And next 30 seconds of their response would be based on that perception. If you make a favourable initial impression, your next 30 seconds will be easy, otherwise you'll spend those 30 seconds proving that you're not some desperate credit card salesman. So, you just have to make sure of the following things while grooming:</p>
        <ol>
            <li>You can wear anything you want eg shirt with trousers; jeans with shirts or t shirts, given that they're clean, ironed and fitting.</li>
            <li>If you're wearing spectacles, it's all right. You dont need to change them.</li>
            <li>Get your beard trimmed and shaped; or get clean shaved</li>
            <li>Get a haircut, every ten days. Just a basic haircut will do, nothing special.</li>
            <li>Your shoes should be clean.</li>
            <li>At the end, you should just look a cultured guy with some value. That's it. Don't think about it more than this. It will just waste your valuable time.</li>
        </ol>
    </section>
    <section>
        <h2>If you're a woman</h2>
        <p>Grooming matters more in your case. But still, self confidence, communication and sub communications hold immensly more importance than it. If you're very well dressed and lack confidence, you'll sabotage yourself before anyone else can do so! Also you don't need to spend a lot of money on shopping for clothes and stuff. Women's clothes are generally more economical than men. So spend your sweet time and spend as much time as you want on grooming, but don't forget the other aspects.</p>
    </section>    
    <p>So, the next step for you is to get your clothes on order, clean them, iron them, clean your shoes, women - get your eyebrows and hair styling done. Guys - you need to sort out the basic things as mentioned above. Take three days for it (one day grace period, in case you want to do a minor shopping.) </p>

    </div>
  )
}