import Head from 'next/head'
import Link from 'next/link';

export default function Articles() {
  return (
    <div>
      <Head>
        <title>Aricles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Articles</h1>
        <ul>
            <li>Read and understand <Link href='/articles/read'><a >click here</a></Link></li>
            <li>Principle for working of this system <Link href='/articles/principle'><a >click here</a></Link></li>
            <li>Positivity <Link href='/articles/positivity'><a >click here</a></Link></li>
            <li>Grooming <Link href='/articles/grooming'><a >click here</a></Link></li>
            <li>Exercising <Link href='/articles/exercising'><a >click here</a></Link></li>
            <li>Body language <Link href='/articles/bodylanguage'><a >click here</a></Link></li>
            <li>Conversational ninja <Link href='/articles/conversation'><a >click here</a></Link></li>
            <li>Leading to building connection <Link href='/articles/leading'><a >click here</a></Link></li>
            <li>Following up <Link href='/articles/followingup'><a >click here</a></Link></li>
            <li>Practice-1 <Link href='/articles/practice1'><a >click here</a></Link></li>
            <li>Practice-2 <Link href='/articles/practice2'><a >click here</a></Link></li>
            <li>Making mistakes <Link href='/articles/mistakes'><a >click here</a></Link></li>
            <li>Procrastination <Link href='/articles/procrastination'><a >click here</a></Link></li>
            <li>Neediness <Link href='/articles/neediness'><a >click here</a></Link></li>

        </ul>
      </main>

    </div>
  )
}