import Head from 'next/head'

export default function Leading() {
  return (
    <div>
      <Head>
        <title>Leading</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lead and shift</h1>
    <p>This one step will amplify the connection betwwen you and the person you're talking to you tens on time in a matter of an hour or so.</p>
    <p>Once you have established the conversation with the person and both are comfortable talking to each other, lead them around. Say to them -"I'm helth concious, if you don't mind let's talk while walking." Then in a couple of minutes - "Say to them let's have a juice or coffee." This way, the more activity you two people do together, the greater connection you'll establish. Stay with them for as long as possible. Don't leave unti atleast an hour. But once it's time to leave, you've to exchange the contact information. Say - "It was pleasure meeting you, I would like to get in touch with you sometime in the future, for <em>name of the activity you enjoyed together</em>. So just just give me your email/mobile number.". For the professional networking purposes, exchanging email is preferrable to phone number. Once you exchange the emails, don't leave immediately! This will demonstrate that you were there for an ulterior motive. Stay a couple of more minutes, and then bid goodbye demontrating that you were really happy meeting them and they made your day.</p>

    </div>
  )
}