import Head from 'next/head'

export default function Mistakes() {
  return (
    <div>
      <Head>
        <title>Making Mistakes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Don't be afraid of making mistakes</h1>
    <p>This is one of the major points that separate those who would be able to learn and use this system effectively and those who won't. Don't take your practice too seriously. Initially, you'll make a lot of mistakes. Your loudness may not be optimum, you may not smile, may not lean back, your eye contact might break frequently, or you may not approach people at all! Don't worry. You just have to take baby steps initially. Don't be too rough on yourself or you'll quickly burn out. You have to be very gradual in taking action. Also, don't set your bars high. This field of developing interpersonal skills is very tricky and full of paradoxes. One may get deluded pretty quickly if they don't understand the principles and have them internalized. If you set your bars high in any other field, like medical or engineering you'll progress, but in terms of developing interpersonal skills, you'll sound needy! So, you have to set your bars low and not be afraid of making mistakes. Initially, your only bar for success should be showing up and completing the tasks. That's it. Don't worry about doing them perfectly on the first or the second attempt, but you should be aware of the ideal and should strive to reach it gradually. So, relax and just show up and you'll succeed!</p>

    </div>
  )
}