import Head from 'next/head'

export default function Neediness() {
  return (
    <div>
      <Head>
        <title>Neediness</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Neediness - will kill your network</h1>
    <p>Don't be needy. Source of neediness is selfishness, and a person is more selfish if they hate people and world in general. So embrace the world and be compassionate towards others. This way you will only think of giving value to others and if you ask for value from them in return, it will also have a basis of a friendly entitlement.</p>
    <p>Also, have confidence in yourself, you've to focus on giving many times more value to people than you expect in return.</p>
    </div>
  )
}