import Head from 'next/head'

export default function Positivity() {
  return (
    <div>
      <Head>
        <title>Positivity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Developing positivity</h1>
        <p>You won't do anything until your mind has a sufficient reason to do so. This is human nature. You won't like meeting people if you don't like them. So, you have to like people. But, you may say that - "People have been extremely mean to me. How can I think good about the world and the people?" You're right, people can be extremely mean, but remember if you keep retaliating to the mean people in kind, it will be you who will lose ultimately, because you'll expend most of your energy meant for your own growth and development, in a conflict. It will also cause you mental and physical issues. So, it is recommended that you keep positive about the people and the world in general. If you want to understand in detail the reason for this, I would suggest that you go and read the seminal book <cite>How to win friends and influence people</cite> by Dale Carnegie</p>
        <p>I would summarize the principles that you would need to follow in order to get the most out of this system:</p>
        <ol>
            <li>Always be positive. Positivity and negativity both come back to you after completing the circle.</li>
            <li>Always appreciate people. Don't flatter, appreciate in a genuine manner. Flattery backfires.</li>
            <li>Never criticize people. Look at the psoitive aspects of even the evil ones. Make it a habit.</li>
            <li>Never get involved in an argument. Even if you win an argument, you'll hurt the ego and pride of your opponent, they will not think highly about you in the future. Always, be polite and try to sort out the argument by reaching a common ground.</li>
            <li>Try to think from other's perspectives and then you'll see why people did what they did, and in doing so you'll develop empathy for the people, resolve the conflicts and go far in life</li>
            <li>Be genuinely interested in people</li>
            <li>Put an effort to remember the names of all the people you meet. For you, it's just the name, but for the other person, it's the most important word in their lives.</li>
            <li>Smile and carry a friendly vibe wherever you go.</li>
            <li>Show respect for other peoples' opinions. Never say - "You're wrong"</li>
            <li>If you're wrong yourself, admit it first and empathically, before the others can point it out. This way people will appreciate your honesty and sincerity.</li>
            <li>Encourage people about their abilities even if they're somewhat lacking. It's better than punishing them for it.</li>
        </ol>
        <p>This is it. This may seem simple, but this is the gist of the mindset you need to have. This is not just Dale Carnegie, but different material and spiritual philosophies have talked about the power of positivity and compassion towards others, and this has been a case for millennia. For example, "Our sorrows and wounds are healed only when we touch them with compassion." ~ Buddha; “Do not seek revenge or bear a grudge against anyone among your people, but love your neighbor as yourself." ~ Bible; "Do everything you have to do, but not with ego, not with lust, not with envy but with love, compassion, humility, and devotion." – Lord Krishna, 'Bhagavad Gita'. Jiddu Krishnamurti said that your self(ego) is not just isolated you, but it is dependent on the relationship with other people and things. So, the biggest quality you got to have is compassion and empathy and then you'll start to genuinely like people and have fun meeting them.</p>
        <p>You don't need to go any deeper beyond this. Just feed these principles to you Anki and actively recall them until they're internalized and you're golden.</p>
    </main>

    </div>
  )
}