import Head from 'next/head'

export default function Practice1() {
  return (
    <div>
      <Head>
        <title>Practice 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Practice-1</h1>
    <p>Now you have necesarry mental mindset and the physical skills to practice in the real world. But as much you practice them at home, you will still make mistakes until you go out and meet real people. So, this is what you're going to do tomorrow. Since you're going to probably make some mistakes in the beginning, it's better to practice at a place where you wouldn't require a second chance, where if you make a mistake, it will be alright. These are the places like malls, meetups not related to your profession, market, etc. Where you don't want to practice your newly acquired skills (until Practice-2), office, wedding of a friend, profession meetup related to your profession, market near your place, your college, etc. anywhere the people would recognize you. Not that it matters too much, but if you make too many mistakes at one place you may be labeled as a creep. So choose places that offer anonymity, for the sake of practice. I'm going to give you a short summary of what you got to do for next 30 days, six days a week.</p>
    <h2>Summary</h2>
    <ol>
        <li>
            <h3>Mindset while going out</h3>
            <ol>
                <li>Be positive</li>
                <li>Be compassionate towards people</li>
                <li>Have a genuinely friendly vibe.</li>
            </ol>
        </li>
        <li>
            <h3>Bodylanguage</h3>
            <ol>
                <li>Be loud</li>
                <li>Smile</li>
                <li>Lean back</li>
                <li>Unbroken eye contact</li>
            </ol>
        </li>
        <li>
            <h3>Magical Talking</h3>
            <ol>
                <li>Internalize your fallback material</li>
                <li>Read the room/venue</li>
                <li>Get ready to implement what you learnt in the "Conversational ninja" exercise</li>
            </ol>
        </li>
    </ol>
    <p>This is all you need to do the upcoming exercise.</p>
    <h2>Exercise</h2>
    <ol>
        <li>Choose a venue a day before, it can be a mall, a market, an event not related to your profession, etc.</li>
        <li>Get groomed and ready</li>
        <li>Use a public transport and show up there</li>
        <li>Using the principles mentioned in the 'Talking magically' you have to make conversation with atleast one person. It can be the cab driver or a copassenger or anyone.</li>
        <li>The conversation, has to be as long as possible. Don't stop the conversation in a couple of minutes, even if it gets a bit uncomfortable. Only leave the conversation once the journey for anyone of you completes or the other person explicitly mentions that they don't want to talk more. Yes. you should not be afraid of getting rejected, that's the point. Take the conversation as long as posssible.</li>
        <li>Once you have built a connection, either exchange number or email.</li>
        <li>When you reach the venue, you have to talk in the same manner as described above to three more people on the first week. From the second week, it will be four and from subsequent weeks it will be five people per day, excluding to one person on the way to your venue</li>
        <li>Ensure that you change your venue every day. You don't want to be doing this a a single venue for more than onece a week.</li>
        <li>When you get back to your home, save the details of the people you interacted with in the spreadsheet.</li>
        <li>You don't need to followup with them at this parctice-1 stage, however, if you find someone of interest to you, you may follow up with them</li>
        <li>That's it. You have begun to develop the skill of effective networking that most of the people don't have.</li>
    </ol>
    </div>
  )
}