import Head from 'next/head'

export default function Practice2() {
  return (
    <div>
      <Head>
        <title>Practice 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Practice-2</h1>
    <p>If you diligently did practice-1 for a month i'm quite sure, you have understood the efectiveness of this system. You would already have added some poeple to your network. If you're still not comfortable with practice-1, you can take fifteen more days to do so, because if you're not at a certain level of comfort while implementing it, you may not be able to do practice-2. Keep increasing the period of practice-1 by fifteen days at a time, until you feel comfortable enough approcachig, interacting, connecting with and exchanginhg contact information with complete strangers. This system is not time bound for practice-1 stage. Also, note that you will never be completely be comfortable approaching and interacting with random people, you just have to be able to develop a ceratin level of confidence in doing so. Perfection is not required. If in a month, you connected with fifteen people and exchanged contact information with 10 people, you're golden.</p>
    <p>Now, at this stage it's the time to go live with your practice. Everything is the same here as with practice-1. Only now you have to choose the venues whre you will find the people you intend to interact and nbetwork with, eg meetups, conferences, professional events etc. Also, note thaht stakes are high in this stage, so be a little cautious, don't be a creep. Keep everything normal and natural. Go and talk to poeple normally and use all the principles of this system summarized in practice-1 stage.</p>
    <p>This is it folks. Network on the above lines and soon you'll find youself at the helm of a large and resourceful network of people who will be willing to help you at every step of your career. You'll also make many lifelong friend in the process. If you like my system don't forget to buy me a coffee!!</p>

    </div>
  )
}