import Head from 'next/head'

export default function Principle() {
  return (
    <div>
      <Head>
        <title>Principle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h1>What is the fundamental principle behind the working of this system?</h1>
        <p>What is it that actually makes a human interation success? Success in the sense that - you get what you want from the person or a group of people you're interacting with.</p>
        <p>Simple answer to these quesions is - peopl will interact will you, respect you or do what you want , if they perceive that you're a person of <strong>high value</strong>. That's it. There is no other magic to it.</p>
        <p>Now, what makes a person high value? Before reading further, think about five things that may make a person high value</p>
        <p>Following are the things that i previously thought make a person high value:</p>
        <ol>
            <li>Money</li>
            <li>Status</li>
            <li>Looks</li>
            <li>Academic background</li>
            <li>Job</li>
            <li>etc.</li>
            <li>Gender</li>
            <li>Celebrity status</li>
        </ol>
        <p>However, one cannot be farther from truth if they think the same. Value of a person is based on the above mentioned things, but it is just a small part of it. Infact, in most of the cases people fail to convey high value irrespective of having most of the above factors working in their favour. For example, a good looking, rich person, who is a CEO of a company, might have very less confidence and hence convey a low value to most of the people around and in turn unable to fully leverage his networking capacity. Although having a actual high value most of the people convey low value to others. So, how can you convey high value?</p>
        <p>If you are clear with certain principles it becomes quite easy to convey high value, and thus fully leverage your capacity of networking skills. Make no mistake, you would still have to practice and internalize the process yourself for a few months before you start getting the real results, but it's eaiser to get to the gist of the things, and directly the hit the bulls eye, rather than fighting for becoming a millionalre, getting a platic surgery, celebrity status etc. and then hpoing to get validation from others. Ofcourse, you shoiuld work hard for a succesful career, but the intent should be for personal satisfaction and not as a way to build a network. Skill of buildding a network is a separate skill in its own right, and it would certainly help with whatever career goal you're pursuing in your life.</p>
        <p>Followng are the effective ways of conveying value, which are independent of your material and social status:</p>
        <ol>
            <li>Self/inner management</li>
            <li>Body language</li>
            <li>Communication Skills</li>
            <li>Social proof</li>
        </ol>
        <p>Yes, these are the only things that matter for effectively conveying high value. There are a few more things that can be done but they're extra, you don't want to be perfect, you want to achive the maximum result possible in the minimum amount of time possible. A person might have a low paying job, unconventional looks, bad academic baackground, etc. they can still convey a massive value if they have appropriate mindset, body language and communication skills.How to get these things sorted out will be dealt in detail in this system.</p>
        <p>Once people feel that you have a high value, they'll either gravitate towards you or will be open to network with you.</p>
    </section>
    </div>
  )
}