import Head from 'next/head'

export default function Principle() {
  return (
    <div>
      <Head>
        <title>Principle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h1>What is the fundamental principle behind the working of this system?</h1>
        <p>What is it that actually makes a human interaction successful? Success in the sense that - you get what you want from the person or a group of people you're interacting with.</p>
        <p>A simple answer to these questions is - that people will interact will you, respect you, or do what you want, if they perceive that you're a person of <strong>high value</strong>. That's it. There is no other magic to it.</p>
        <p>Now, what makes a person high value? Before reading further, think about five things that may make a person high value</p>
        <p>Following are the things that I previously thought make a person high value:</p>
        <ol>
            <li>Money</li>
            <li>Status</li>
            <li>Looks</li>
            <li>Academic background</li>
            <li>Job</li>
            <li>etc.</li>
            <li>Gender</li>
            <li>Celebrity status</li>
        </ol>
        <p>However, one cannot be farther from the truth if one thinks the same. The value of a person is based on the above-mentioned things, but it is just a small part of it. In fact, in most cases, people fail to convey high value irrespective of having most of the above factors working in their favor. For example, a good-looking, rich person, who is a CEO of a company, might have very less confidence and hence convey a low value to most of the people around and in turn unable to fully leverage his networking capacity. Although having an actual high value most people convey low value to others. So, how can you convey high value?</p>
        <p>If you are clear with certain principles it becomes quite easy to convey high value, and thus fully leverage your capacity of networking skills. Make no mistake, you would still have to practice and internalize the process yourself for a few months before you start getting the real results, but it's easier to get to the gist of the things, and directly the hit the bull's eye, rather than fighting for becoming a millionaire, getting plastic surgery, celebrity status, etc. and then hoping to get validation from others. Of course, you should work hard for a successful career, but the intent should be for personal satisfaction and not as a way to build a network. The skill of building a network is a separate skill in its own right, and it would certainly help with whatever career goal you're pursuing in your life.</p>
        <p>Following are the effective ways of conveying value, which is independent of your material and social status:</p>
        <ol>
            <li>Self/inner/psychological management</li>
            <li>Body language</li>
            <li>Communication Skills</li>
            <li>Social proof</li>
        </ol>
        <p>Yes, these are the only things that matter for effectively conveying high value. There are a few more things that can be done but they're extra, you don't want to be perfect, you want to achieve the maximum result possible in the minimum amount of time possible. A person might have a low-paying job, unconventional looks, bad academic background, etc. they can still convey a massive value if they have the appropriate mindset, body language, and communication skills. How to get these things sorted out will be dealt with in detail in this system.</p>
        <p>Once people feel that you have a high value, they'll either gravitate towards you or will be open to networking with you.</p>
    </section>
    </div>
  )
}