import Head from 'next/head'

export default function Procrastination() {
  return (
    <div>
      <Head>
        <title>Procrastination</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Dealing with procrastination</h1>
    <p>There would surely be days when you won't want to go out and network with real people. Following are some of the reasons and their remedies.</p>
    <ol>
        <li>Practice being positive and likeing people. You can do Metta meditation. Check out the "Guided Metta meditation by Sharon Salzberg". Do this for 10 minutes everyday after waking up and before sleeping. This meditation is very effective for conditioning your mind to be positive and compassionete.</li>
        <li>If you are not clear with the process and hence don't trust it: to make this process work you have to first understand it and then give it a try. Without giving it a try for atleast fifteen days you won't get proof of its effectiveness. So bite the bullet and do the activities.</li>
        <li>Babystep if you don't feel like doing it. Just get up to take a bath without thinking anything, then just get ready and then just leave and show up to any venue you feel most comfortable with. Before that don't think about approaching and interacting with people</li>
        <li>Don't make it too harsh on yourself. You have to get out of your comfortzone a little bit ever time you go out and practice. Going out of your comfortzone is very important but fi you do it too much, you may get burnt out.</li>
        <li>Realise that, it is initially diffiult for everyone. What seperates the winners from the loosers is the sheer determinstion of just showing up and doing it.</li>
    </ol>
    </div>
  )
}