import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Aboutme.module.css'
import mypic from '../../public/images/archit.jpg'

export default function Aboutme() {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainClass}>
        <section>
            <h1>Hi! My name is Archit...</h1>
            <p>I'm a software engineer and a social dynamics coach by profession. I am passionate about how human interactions work and I have been learning, researching and teching social synamics for almost last ten years. I have spent countless hours in simplifying this process to a kind of bare skeleton of principles which can be learnt and used effectively by most of the people. </p>
            <h2>My past</h2>
            <p>I had been a very shy and introverted guy since my childhood. I was unable to communicate effictively due to my introversion. This continued till my college. Then I decided to take matters into my own hands and learn about human communication and behaviour. I studied a lot of psychology, self help and books about human behaviour. However, more I read the more confused I got. Then one day I found a community of like minded invdividuals who were working to study and learn about the same area. I took mentorship from  a few of them. They took me out into to the real wold and made me approach and interact with people. From day one itself I understood that my life would now never be the same. They taught me concreate and actionable steps that i learned and improvised with great diligence over the years. I realised this skill coudn't be learnt by reading books or in the colleges, but it can be learnt gradually by deliberately, systematically and consistently interacting with large number of people. </p>
        </section>
        <section>
            <Image 
              src={mypic} 
              alt="archit" 
              width= "100%"
              height="100%"
              layout='responsive'
              className={styles.Aboutme}
            />
        </section>
        </main>

        <section>
            <h2>As a coach</h2>
            <p>From 2018 beginning, I started teaching this system all over India. I usually took three days bootcamps. I quickly gained clientele from diverse professional fields. This has been the most satisfying things that I have done in my life. </p>
        </section>
        <section>
            <h2>Currently</h2>
            <p>Since the COVID-19 began I started givin online consulting. Also, I came to realise that many of my prospects were impacted financially by the pandemic. Therefore, i further streamlined this system and started provding this system online free of cost. For thos who have any doubts reagrding this, I have kept my email open and also written number of articles (prestent in the Article section) to help people understand the system and its underlying concepts better. Also, for those who have further doubts I have kept open the paid options of online consultation and bootcamps. However, they're not mandatory and with a certain amount of effort you should be able to achieve the desired results by yourselves.</p>
        </section>

    </div>
  )
}