import Head from 'next/head'
import styles from "../styles/Contact.module.css"

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainClass}>
        <h1>You can contact me at: </h1>
        <span><a href="mailto:architc.official@gmail.com">architc.official@gmail.com</a></span>
        </main>
    </div>
  )
}