import Head from 'next/head'
import styles from "../styles/Contact.module.css"

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Networkmallo: Contact</title>
        <meta name="description" content="Contact Learn the art of realtime networking" />
        <meta property="og:description" content="Contact Learn the art of realtime networking" />
        <meta property="og:title" content="Contact Networkmallo" />
        <meta name="keywords" content="social networking,lifestyle coach,networkmallo,network mallo" />
        <meta property="og:url" content="https://networkmallo.com/contact" />
        <meta property="og:type" content="website" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Head>
          <title>Contact me</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.mainClass}>
          <h1>You can contact me at: </h1>
          <span><a href="mailto:architc.official@gmail.com" aria-label="author contact email">architc.official@gmail.com</a></span>
          </main>
      </div>
    </div>
  )
}