import Head from 'next/head'

export default function Services() {
  return (
    <div>
      <Head>
        <title>Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ul>
            <li>
                <h2>Personal Consultation</h2>
                <p></p>
            </li>
            <li>Personal Training</li>
            <li>Book</li>
        </ul>
      </main>

    </div>
  )
}