import Head from 'next/head'
import Link from 'next/link';

export default function System() {
  return (
    <div>
      <Head>
        <title>Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>This system is divided into two parts:</h1>
        <ul>
            <li>Inner development</li>
            <li>Outer skills</li>
        </ul>
        <p>These two parts are not strictly exclusive and correct understanding and implementation of one will undoubtedly impact the other. Therefore, you should strive to perfect both of them in a balanced manner.</p>
    </main>
    <section>
        <h2>Inner development</h2>
        <p>This part deals with your inner or psychological management, that is</p>
        <ul>
            <li>How do you deal with your frustrations?</li>
            <li>What is your current level of self confidence and self esteem and how you deal with it?</li>
            <li>What is your general perspective/belief about the nature of the world and the people?</li>
            <li>How much self-discipline, and self-control do you have?</li>
            <li>How consistent you are in what you do?</li>
            <li>How do you deal with your fears?</li>
            <li>What is your level of desire to achieve the required results?</li>
        </ul>
        <p>Ideally, if you have a perfectly developed inner self you would not require any outer skills. But since that is not the case, we have to approach both of these together.</p>
    </section>
    <section>
        <h2>Outer skills</h2>
        <p>This part deals with developing the skill set necessary for developing your communication and networking muscles. It is as important as inner development.</p>
    </section>
    <section>
        <h2>How to use this system?</h2>
        <p>Firstly, trust the system. Just give it a couple of weeks of practice. It will be very difficult during the first few days to a week, but if you take massive action amidst discomfort, you'll start enjoying it and the results will start showing up really fast.</p>
        <p>Secondly, before implementing get as much understanding of the concepts behind the system as you can. Do this by going to the articles section and reading all the articles. Also, remember don't get into the trap of reading the psychology and self-help material on the internet. For at least a month or so avoid the temptation of reading the external self-development or personality development books/videos/articles. The articles I have written are sufficient and then all you require is to learn through practice. In case it doesn't work out for a month, you can always do whatever you want. So take a week or so to read all the articles and get the gist behind them.</p>
        <p>Once you have read and understood most of the articles, we will start implementing the system.</p>
        <h2>Implementing the system:</h2>
        <ol>
            <li>Read and understand all the articles <Link href='/articles' ><a>click here</a></Link>  
            </li>
            <li>Take a break. After you have done the reading, take a day off. Relax. Engage in your favourite hobby or just chill out.</li>
            <li>Now, start the practices mentioned in the articles section one by one until you become a networking ninja.</li>
        </ol>
    </section>

    </div>
  )
}