import Head from 'next/head'

export default function Read() {
  return (
    <div>
      <Head>
        <title>Read and understand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Terms and conditions</h1>
        <p>It is upon the reader to practice or not practice the material contained in this website. There is no compulsion by the author to do so.</p>
        <p>Contents of this website are the creation of the author and are copyrighted.</p>
       </main>

    </div>
  )
}